/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_products_manager;

/**
 *
 * @author Administrator
 */

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;



public class ManageProducts_Frame extends javax.swing.JFrame {

    /**
     * Creates new form ManageProducts_Frame
     */
    
    //create border
    Border panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.darkGray);
    Border textField_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.darkGray);
    
    //arraylist of products
    ArrayList<Product> productsArray = new ArrayList<>();
    
    
    // initialising int variable for navigation
    int position = 0;
    
    Database database = new Database();
    
    public ManageProducts_Frame() {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
        
        //set border
        jPanel_Container.setBorder(panel_border);
        txt_name.setBorder(textField_border);
        txt_quantity.setBorder(textField_border);
        txt_price.setBorder(textField_border);
        txt_image.setBorder(textField_border);
        
        
        // initiate functions
        database.DatabaseCreate();
        refreshTable();
                
                
        // checks list has data before displaying list items
        int itemsInList = getProductsList().size();
        
        if(itemsInList > 0)
        {
            showProductData(0);
        }
        
        
        
        //change rowHeight of table
        jTable_products.setRowHeight(35);
    }

    // create a function to display image into jlabel_Image box
       public void displayImage(String imgPath, JLabel label){
           ImageIcon imgIco = new ImageIcon(imgPath);
           Image img = imgIco.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
           label.setIcon(new ImageIcon(img));
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Container = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinner_ID = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_image = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jComboBox_category = new javax.swing.JComboBox<>();
        btn_edit = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        btn_browse = new javax.swing.JButton();
        txt_price = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_previous = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Container.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Container.setName(""); // NOI18N
        jPanel_Container.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_ContainerComponentShown(evt);
            }
        });

        jLabel_Close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Quantity", "Price", "Quantity"
            }
        ));
        jTable_products.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jTable_products.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable_productsComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name:");

        jSpinner_ID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Quantity:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Image:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Price:");

        txt_quantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });
        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quantityKeyTyped(evt);
            }
        });

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_image.setEditable(false);
        txt_image.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lbl_image.setBackground(new java.awt.Color(102, 102, 102));
        lbl_image.setOpaque(true);

        jComboBox_category.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cars", "Electronics", "Toys", "Clothes" }));

        btn_edit.setBackground(new java.awt.Color(0, 0, 0));
        btn_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(0, 0, 0));
        btn_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_remove.setBackground(new java.awt.Color(0, 0, 0));
        btn_remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        jButton_Search.setBackground(new java.awt.Color(255, 102, 0));
        jButton_Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jButton_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_SearchKeyPressed(evt);
            }
        });

        btn_browse.setBackground(new java.awt.Color(255, 102, 0));
        btn_browse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_browse.setForeground(new java.awt.Color(255, 255, 255));
        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        txt_price.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_priceKeyReleased(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 0, 0));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_first.setBackground(new java.awt.Color(102, 0, 0));
        btn_first.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_first.setForeground(new java.awt.Color(255, 255, 255));
        btn_first.setText("<<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_previous.setBackground(new java.awt.Color(102, 0, 0));
        btn_previous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_previous.setForeground(new java.awt.Color(255, 255, 255));
        btn_previous.setText("<");
        btn_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previousActionPerformed(evt);
            }
        });

        btn_next.setBackground(new java.awt.Color(102, 0, 0));
        btn_next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 255, 255));
        btn_next.setText(">");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setBackground(new java.awt.Color(102, 0, 0));
        btn_last.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_last.setForeground(new java.awt.Color(255, 255, 255));
        btn_last.setText(">>");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        jButton_Cancel.setBackground(new java.awt.Color(255, 102, 0));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        jButton_Cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContainerLayout = new javax.swing.GroupLayout(jPanel_Container);
        jPanel_Container.setLayout(jPanel_ContainerLayout);
        jPanel_ContainerLayout.setHorizontalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name)
                                    .addComponent(jComboBox_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_quantity)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_price))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ContainerLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        jPanel_ContainerLayout.setVerticalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Product> getProductsList(){
      
          
            ArrayList<Product> list = new ArrayList<>();
            String sql = "select * from Products";
            
            Statement stmt;
            ResultSet rs;
            
        try { 
            // Load SQLLITE Database
            Connection con = database.DatabaseConnection();
            
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            Product product;
            
            while(rs.next()){
                product = new Product(rs.getInt("id"), rs.getString("name"),
                        rs.getString("category"), rs.getInt("quantity"),
                        rs.getDouble("price"), rs.getString("image_path"));
                
                list.add(product);
            }
            
            
        } 
        catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Oops, something went wrong on: " + ex.getMessage());
        }
        productsArray = list;
        return list;
    }

    public void showProductData(int index){
        jSpinner_ID.setValue(getProductsList().get(index).getId());
        txt_name.setText(getProductsList().get(index).getName());
        jComboBox_category.setSelectedItem(getProductsList().get(index).getCategory());
        txt_quantity.setText(getProductsList().get(index).getQuantity().toString());
        txt_price.setText(getProductsList().get(index).getPrice().toString());
        txt_image.setText(getProductsList().get(index).getImage_path());
        displayImage(getProductsList().get(index).getImage_path(), lbl_image);
    }
    
    // create a function to check empty fields
    public boolean checkEmptyFields(){
        String name = txt_name.getText().trim();
        String quantity = txt_quantity.getText().trim();
        String price = txt_price.getText().trim();
        String imagePath = txt_image.getText().trim();
        
        return !((name.equals("") || quantity.equals("") || price.equals("") || imagePath.equals("")));
    }
            
    public void refreshTable(){
         try {
            // Load SQLLITE database
            
            Connection con = database.DatabaseConnection();
            
            Statement stmt = con.createStatement();
            
            String sql = "select * from Products";
            ResultSet rs = stmt.executeQuery(sql);
            
            // code to clear table before viewing
            DefaultTableModel tableModel = (DefaultTableModel)jTable_products.getModel();
            tableModel.setRowCount(0);
            
            while(rs.next()){
            
            //data will be added until finish
            String id = String.valueOf(rs.getInt("id"));
            String name = rs.getString("name");
            String category = rs.getString("category");
            String quantity = String.valueOf(rs.getInt("quantity"));
            String price = String.valueOf(rs.getDouble("price"));
            String image_path = rs.getString("image_path");
            
            
            //string array for store data into jtable
            String tbData[] = {id,name,category,quantity,price,image_path};  
            DefaultTableModel tblModel = (DefaultTableModel)jTable_products.getModel();
            

            //add string array data into jTable
            tblModel.addRow(tbData);
            }
        } 
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Oops, something went wrong on: " + ex.getMessage());
        }
    }
    
    // function to clear fields
    public void clearFields(){
        jSpinner_ID.setValue(0);
        txt_name.setText("");
        txt_quantity.setText("");
        txt_price.setText("");
        jComboBox_category.setSelectedIndex(0);
        txt_image.setText("");
        lbl_image.setIcon(null);
    
    }
    
    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        
        if(checkEmptyFields()){
            
            int id = (int) jSpinner_ID.getValue();
            String name = txt_name.getText();
            String category = (String) jComboBox_category.getSelectedItem();
            double price = Double.parseDouble(txt_price.getText());
            int quantity = Integer.parseInt(txt_quantity.getText());
            String image_path = txt_image.getText();

            database.EditProduct(name,category,quantity,price,image_path,id);
            clearFields();
            refreshTable();
           
        }
        else{
            System.out.println("No empty fields");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        if(checkEmptyFields()){
            String name = txt_name.getText();
            String category = (String) jComboBox_category.getSelectedItem();
            double price = Double.parseDouble(txt_price.getText());
            int quantity = Integer.parseInt(txt_quantity.getText());
            String image_path = txt_image.getText();
            
            database.InsertProduct(name,category,quantity,price,image_path);
            clearFields();
            refreshTable();
            
        }
        else{
            System.out.println("No empty fields");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
           if(checkEmptyFields()){ 
                int id = (int) jSpinner_ID.getValue();


                  database.DeleteProduct(id);
                  clearFields();
                  refreshTable();
           }
           else{
                System.out.println("No empty fields");
                }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        if(checkEmptyFields()){ 
            try {
                 int id = (int) jSpinner_ID.getValue();

                // Load SQLLITE database 
                
                Connection con = database.DatabaseConnection();
                Statement stmt = con.createStatement();

                String sql = "select * from Products where id =" + id;

                ResultSet rs = stmt.executeQuery(sql);


                // code to clear table before viewing
                DefaultTableModel tableModel = (DefaultTableModel)jTable_products.getModel();
                tableModel.setRowCount(0);

                if(rs.next()){

                //data will be added until finish
                String recordid = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String category = rs.getString("category");
                String quantity = String.valueOf(rs.getInt("quantity"));
                String price = String.valueOf(rs.getDouble("price"));
                String image_path = rs.getString("image_path");


                //string array for store data into jtable
                String tbData[] = {recordid,name,category,quantity,price,image_path};  
                DefaultTableModel tblModel = (DefaultTableModel)jTable_products.getModel();


                //add string array data into jTable
                tblModel.addRow(tbData);
                }

                else{
                    JOptionPane.showMessageDialog(null, "Product does not exist.");
                }
            } 
            catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Oops, something went wrong on: " + ex.getMessage());
                }
            } 
        else{
            System.out.println("No empty fields");
        }    
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*images",".png","jpg",".jpeg ");
        filechooser.addChoosableFileFilter(filter);
        
        if(filechooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
            File selectedImage = filechooser.getSelectedFile();
            String image_path = selectedImage.getAbsolutePath();
            txt_image.setText(image_path);
            displayImage(image_path, lbl_image);
            System.out.println(image_path);
        }
        else{
            System.out.println("no file selected");
        }
    }//GEN-LAST:event_btn_browseActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        // TODO add your handling code here:
            int index = jTable_products.getSelectedRow();
            showProductData(index);
            position = index;
    }//GEN-LAST:event_jTable_productsMouseClicked

    private void jTable_productsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable_productsComponentShown
        
    }//GEN-LAST:event_jTable_productsComponentShown

    private void jButton_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_SearchKeyPressed
        // TODO add your handling code here:
       
    
    }//GEN-LAST:event_jButton_SearchKeyPressed

    private void jPanel_ContainerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_ContainerComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel_ContainerComponentShown

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
        try{
            position = 0;
            showProductData(0);
            jTable_products.setRowSelectionInterval(position, position);
        }
         catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No more products");
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        // TODO add your handling code here:
        try{
            position--;
            if(position < 0){
                position = 0;
            }
            showProductData(position);
            jTable_products.setRowSelectionInterval(position, position);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No more products");
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
         // TODO add your handling code here:
         try{
            position++;
            if(position > getProductsList().size() - 1){
                position = getProductsList().size() - 1;
            }
            showProductData(position);
            jTable_products.setRowSelectionInterval(position, position);
         }
          catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No more products");
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
        try{
            position = getProductsList().size()-1;
            showProductData(position);
            jTable_products.setRowSelectionInterval(position, position);
        }
         catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No more products");
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void txt_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyTyped
        // allow only numbers or you can use jspinner
        
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_quantityKeyTyped

    private void txt_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyReleased
        // TODO add your handling code here:
        try{
            Double.valueOf(txt_price.getText());
        }
        catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            txt_price.setText("");
        }
    }//GEN-LAST:event_txt_priceKeyReleased

    private void txt_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyReleased
        // TODO add your handling code here:
        try{
            Integer.valueOf(txt_quantity.getText());
        }
        catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            txt_quantity.setText("");
        }
    }//GEN-LAST:event_txt_quantityKeyReleased

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_CancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CancelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CancelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JPanel jPanel_Container;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_ID;
    private javax.swing.JTable jTable_products;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_image;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
